name: Update Repo List

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README with repos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "repos"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          feed_list: "https://github.com/shrijal10333?tab=repositories"
